### ISSUE TITLE
We need a DIC

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#100]
We have a serious dependency chain; which is actually a good thing as long as everything stays as it is. But changing a dependency right now forces me to fix countless occurrences and test as well. This should not be necessary in a perfect world ;-) ...

**Comment by stefanrinderle** [comment]
I read about DI in react and it seems like InversifyJS is the best fitting solution.

**Comment by stefanrinderle** [comment]
The pull request #121 switches to InversifyJS dependency injection for all services where we create an instance from.

I'm not sure if we should use DI also for stores. On the one hand it would be easier to get the required store at the required component without the need to give it through multiple components in the hierarchy. On the other hand store updates should propagade through the hierarchy of the components which is then nicer to see int the implementation.

@Ungolianth What do you think here?

**Comment by stefanrinderle** [comment]
I would like to move the discussion here and not in the pull request, it will be easier to find later if we want to look at the reasons why we did something...

@Ungolianth's comment:
I'm not starting a code review, because there's a lot of general stuff I want to talk about first:

# Decentralised Construction / Configuration
Right now the container is created and initially configured/filled at `inversify.config.ts`. Then on runtime `app.tsx` registers 8 more services (some directly, some indirectly). Was there a specific reason to not have the DIC created, configured and managed from a single location (like eg. an Abstraction or even Inherited Class from `Container`)?

# Lazy Injection vs. Tests
How well does lazy injection work with tests? Is easily possible to replace all "lazy dependencies" with mocks? I don't want to reconfigure the DIC for every test...

Is [constructor injection](https://github.com/inversify/InversifyJS/blob/master/wiki/constructor_injection.md) an option with React?

# Lazy Loading
Usually a DIC will create objects when they are first requested. This keeps the memory usage to a minimum, when only a limited path within the program is used. The way our DIC is created, we just don't have lazy loading.  Every class is instantiated and then stored on the container configuration.

# Stores should be part of the DI
At least it should be ensured, that by default all class instantiations can are configured to use the same stores. Otherwise I feel like we are missing a lot of value the DI should offer.

**Comment by stefanrinderle** [comment]
My "answers":

h3. Decentralised Construction / Configuration

The container bindings are currently done in the app.tsx because the services need the stores in the constructors. I wanted to be sure that we use really the same stores to keep the amount of changes to a minimum. If all classes have "zero parameter" constructors, the instantiation could/should be moved to the inversify.config.ts. In the end, I also want the app.tsx clean from DI stuff. I just didn't want to have to refactor the whole application if we come to another approach...

h3. Lazy Injection vs. Tests

Works great:
`const testSonarService = Sinon.createStubInstance(SonarQubeMeasuresService);
bindMock("SonarQubeMeasuresService", testSonarService);`

h3. Constructor injection

Constructor injection worked, but i personally prefer parameter injections. They didn't work without lazyInjection that's the main cause why i use it ;-) I do not have a string opinion on that. But the way it is currently it the cleanest way to do it (incl. tests) for now.

h3. Lazy Loading

Yes, that's right. But as long as not all objects which are needed are "injectable" and therefore do not have "zero param constructors" this is hard to achieve. But it would be great to have this in the future.

h3. Stores part of the DI

The way the binding is made currently - manually in the app.tsx or inversify.config.ts - this can be achieved easielly. The method:`toConstantValue` prevents lazy loading and always returns the same instance of the class.

**Comment by Ungolianth** [comment]
I have to admit, that I'm not sold on the whole lazy injection, but I can't put my finger an something specific (yet)... 

I did prepare an example without lazy inject, just the way it's proposed in the introduction. Maybe you can have a look at it and tell me what you think (and why lazy injection is better) ;-)

[inversify_no_lazyinject.zip](https://github.com/stefanrinderle/softvis3d/files/1052485/inversify_no_lazyinject.zip) - extract, then apply patch (using your JetBrains IDE, not git cli)

**Comment by stefanrinderle** [comment]
As already said, lazyInject is not really a thing for me. I just wanted to use parameter injection instead of constructor injection i this did not work without lazy injection. I know this is not a real reason, but i just wanted to get started with something.

I like the approach you've done in the patch. But i would like to discuss between constructor and parameter injection. For me, the advantages of parameter injection are:

* Zero argument constructor which is easier for tests
* Only mock the objects in the test which you need.
* No need to change the constructors of the class in all tests if a new dependency is added

So, mostly test stuff. And I'm more used to it, as it is more common to use property injection in java.

As always, i can also live with the constructor injection, just wanted to discuss this one more time ;-)
