### ISSUE TITLE
Update UI concept

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#13]
Based on the server side layout approach, the current UI has three parts:

Select modal dialog
- Select the metric and trigger the layout and visualization

Toolbar (could be renamed to e.g. Details)
- Show current status of the visualization (current metric names)
- Show the current selected item with name, parent and children info
- "Action buttons" to focus on a specific part of the visualization or reset this to show all objects

Help modal dialog
(Re-)Select / Hide / Show one of the dialogs above with little buttons on the bottom right

As we create the layout in the frontend and faster as before, we could make the UI more interactive and rethink the current structure. I think of the following things:

- I would keep the initial modal dialog to be able to explain the user the basic stuff and help to select adequate metrics.
- The current help extra dialog should be integrated into the initial modal dialog
- The little buttons on the bottom right corner should be moved to the top left (because there is always a white space in the 3D visualization
- I think that the toolbar could stay as is for the first step, but the inner css should be updated. A better margin of the text, more "focus" on the selected object, ...
- Overall, the CSS is not really good. With the toolbar css refactoring, all the other "components" should be updated as well
- The space for the little buttons on the top left could be extended to give the user a more interactive experience. Select layout algorithm, select linear/log calculation, ...

**Comment by Ungolianth** [comment]
![soft-concept](https://cloud.githubusercontent.com/assets/13331717/15455601/6bfbcbf2-2059-11e6-8414-044c4bd45952.jpg)

Concept Idea...

**Comment by stefanrinderle** [comment]
Looks very good. I think we can start with that.

**Comment by Ungolianth** [comment]
I'd have to change a lot of stuff in the AngularJS-Controllers to implement the many of the ideas in the concept idea. Since we plan on rewriting the UI on a completely new Framework anyway, I tried to reduce the required changes to a minimum, while fixing a few bugs and polishing the UI.

We should not discard this Issue though, as many good ideas were not yet implemented. Maybe Assign it to a new Milestone (GUI/Frontend/Framework-Refactoring)?

@stefanrinderle: If you approve the changes and have nothing to add, i will create a pull request for [Branch new-ui](../tree/13-new-ui).


# Changes:
 * [Feature] Toolbar is always maxed out
 * [Feature] Color scheme is now white-grey with hint of blue (just like sonar)
 * [Bugfix] Prevent X-Scrolling by allowing word-wrap.
 * [Bugfix] Unnecessary Scrollbars have been eliminated
 * [Bugfix] Plugin uses all available Space in all Browsers

------------------------------------------------
![2016-06-10 14_03_34-sonarqube - argouml](https://cloud.githubusercontent.com/assets/13331717/15963692/426d881a-2f14-11e6-87d5-4ec0ed4a6b0c.png)

**Comment by stefanrinderle** [comment]
Looks great. Especially the updated color concept and the removal of the unneeded scroll bars. Now it doesn'l look like a "backend guy frontend implementation" anymore. Really thanks for that.

According to the issue I'm a big fan of closing thinks and open others. So I would close this one after merging and open a new issue for the remaining changes or to keep track of new UI ideas. Concerning the milestones, i would leave it with the ones we already have. After we are finished with all the stuff for the current milestone, we can then select the stories for the next one and move all others in a new milestone. What do you think?

**Comment by Ungolianth** [comment]
I'm also fine with that, since closed issues are still available for reviews.

I created issue #20, which in itself is gonna be a monster. But a monster, that contains the a structured UI :wink:
