### ISSUE TITLE
Descriptions for advanced options

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#65]
Like the default options all the advanced options should also have a description.

**Comment by stefanrinderle** [comment]
* Metric descriptions are available through the SQ metric api
* It was needed to refactor the profile objects to only carry the metric id because the metric values are only available after the metric initialization is finished
* We keep (and maintain) the color metrics by ourselves to be able to add a "color centric" description

**Comment by stefanrinderle** [comment]
Added scale descriptions. I tested the different settings and I'm not really sure if there is really a difference. Especially linear scaled and linear does not result in a difference. Does this really work?

@Ungolianth: Could you take a look at this?

**Comment by Ungolianth** [comment]
I can recall we had a few discussions about the exact behavior of the scaling methods; so I summarized them and created an article over [here](https://github.com/stefanrinderle/softvis3d/wiki/Scaling-algorithms-(Writeup)).

But to answer your question: It really works :suspect:

**Comment by stefanrinderle** [comment]
Great, thanks for the detailed explanation page. I will add a link to this from the softvis3d.com help section.
